# Generated by Django 2.1.4 on 2018-12-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20181218_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='report',
            name='vehicle_plate',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
    ]
