# Generated by Django 2.1.4 on 2018-12-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20181219_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_plate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicle_plate',
            name='user_link',
        ),
        migrations.AlterField(
            model_name='report',
            name='vehicle_plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plate.Vehicle_plate'),
        ),
        migrations.DeleteModel(
            name='Vehicle_plate',
        ),
    ]
