# Generated by Django 2.1.4 on 2018-12-29 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='report.Report'),
        ),
        migrations.AlterField(
            model_name='like',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='report.Report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Расскажите подробнее (Необязательно)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='header',
            field=models.CharField(help_text='До 100 символов', max_length=100, verbose_name='Что случилось?'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image_report',
            field=models.ImageField(blank=True, help_text='На фото должно быть видно номер автомобиля!', null=True, upload_to='report/images/', verbose_name='Загрузите Ваше Фото'),
        ),
        migrations.AlterField(
            model_name='report',
            name='video_link_report',
            field=models.URLField(blank=True, help_text='YouTube', null=True, verbose_name='Ссылка на видео'),
        ),
    ]
